attendee/urls.py
from django.conf.urls import url
from django.urls import path

from attendee import views


app_name = 'attendee'
urlpatterns = [
    path('show_event/<int:event_id>/', views.show_event, name='show_event'),
]

event/urls.py
from django.conf.urls import url
from event import views as event_views
from dashboard import views as dashboard_views

urlpatterns = [

	url(r'^create/$', event_views.create_event, name='create_event'),
	url(r'^(?P<event_id>\d+)/edit/$', event_views.edit_event, name='edit_event'),
	url(r'^(?P<event_id>\d+)/details/$', event_views.view_event, name='view_event'),
	url(r'^(?P<event_id>\d+)/qr/$',event_views.show_event_qr, name='view_event_qr'),
	url(r'^(?P<event_id>\d+)/dashboard/$',dashboard_views.view_dashboard, name='view_dashboard'),
	url(r'^(?P<event_id>\d+)/dashboard/questions/$',dashboard_views.session_data, name='session_data'),
	url(r'^(?P<event_id>\d+)/addquestion/$',event_views.add_question, name='add_question'),
	url(r'^toggleactive/(?P<question_id>\d+)$',event_views.toggle_status, name='toggle_status'),
]

feedback/urls.py
from django.urls import path
from feedback import views
#import eventcoord
urlpatterns = [
	path('<slug:event_id>', views.feedback, name='receive_feedback'),
]

multichat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from fil_auth.views import auth_test
from administrator import urls as admin_urls
from coordinator import urls as coord_urls
from feedback import urls as feedback_urls
from event import urls as event_urls
from presenter import urls as persenter_urls
from dashboard import urls as dashboard_urls


urlpatterns = [
    url(r'^$', auth_test, name='index'),  # The start point for index view
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin_urls)),
    url(r'^feedback/', include(feedback_urls)),
    url(r'^coord/', include(coord_urls)),
    url(r'^dashboard/', include(dashboard_urls)),
    url(r'^event/', include(event_urls)),
    url(r'^presenter/', include(persenter_urls)),
    url(r'^accounts/login/$', logout, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),  # The base django logout view
    url(r'^django-admin/', admin.site.urls),  # etc :D
]

event/models.py
from django.db import models
from fil_auth.models import CustomUser
import uuid
# Create your models here.

class Event(models.Model):
    """
    Events Model
    """
    # id = models.IntegerField(primary_key=True, max_length=64, verbose_name=u"Event Id")
    event_name = models.CharField(max_length=200)
    timestamp = models.DateTimeField()
    duration = models.IntegerField()
    coordinator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)


class QuestionType(models.Model):
    question_type = models.CharField(max_length=100)
    def __str__(self):
        return self.question_type


class Question(models.Model):
    question_text = models.CharField(max_length=500, null=False)
    event = models.ForeignKey(Event, null=False, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False)
    is_mandatory = models.BooleanField(default=False)
    question_type = models.ForeignKey(QuestionType, on_delete=models.CASCADE)


class Choice(models.Model):
    """There will be three type of choices->
    multi-select,single choice&rating corresponding to any question_id.
    """
    choice_text = models.CharField(max_length=200)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)

event/forms.py
from django import forms
from django.forms import ModelForm
from event.models import Event, QuestionType

class EventForm(forms.Form):
	event_name = forms.CharField(max_length=200)
	date_event = forms.DateTimeField()
	duration = forms.IntegerField()
	description = forms.CharField(widget=forms.Textarea)

class NewQuestionForm(forms.Form):
	question_text = forms.CharField(max_length=200)
	is_active = forms.BooleanField(widget=forms.CheckboxInput, required=False)
	is_mandatory = forms.BooleanField(widget=forms.CheckboxInput, required=False)
	question_type = forms.ModelChoiceField(queryset = QuestionType.objects.all())

event/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from event.models import Event, Question, QuestionType,Choice
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from event.forms import EventForm, NewQuestionForm
from dashboard.views import view_dashboard
import uuid
import json
from django.http import JsonResponse
# Create your views here.


@user_passes_test(lambda u: u.is_ecoord or u.is_superuser)
@login_required
def create_event(request):
    """Create a new event."""
    new_event_form = EventForm()
    if request.method == 'POST':
        response_new_event_form = EventForm(request.POST)
        print(response_new_event_form)
        if response_new_event_form.is_valid():
            event_name = response_new_event_form.cleaned_data['event_name']
            date_event = response_new_event_form.cleaned_data['date_event']
            duration = response_new_event_form.cleaned_data['duration']
            coordinator = request.user
            description = response_new_event_form.cleaned_data['description']
            Event.objects.create(event_name=event_name, timestamp=date_event,
                                 duration=duration, coordinator=coordinator, description=description)
            print("saved event")
            return HttpResponseRedirect(reverse('coord_main_panel'))

        else:
            print("error")
            return render(request, 'event/new_event_form.html', {'form': new_event_form})

    return render(request, 'event/new_event_form.html', {'form': new_event_form})


@user_passes_test(lambda u: u.is_ecoord or u.is_superuser)
@login_required
def edit_event(request, event_id):
    """Edit event."""
    event_details = Event.objects.get(pk=event_id)
    event_data = {	'event_name': event_details.event_name,
                   'date_event': event_details.timestamp,
                   'duration': event_details.duration,
                   'description': event_details.description}
    descriptionfield = event_details.description

    populated_form = EventForm(event_data, initial=event_data)

    if request.method == 'POST':
        changed_event_details = EventForm(request.POST)
        if changed_event_details.is_valid():
            event_name = changed_event_details.cleaned_data['event_name']
            date_event = changed_event_details.cleaned_data['date_event']
            duration = changed_event_details.cleaned_data['duration']
            coordinator = request.user
            description = changed_event_details.cleaned_data['description']
            Event.objects.filter(pk=event_id).update(event_name=event_name, timestamp=date_event,
                                                     duration=duration, coordinator=coordinator, description=description)
            print("saved event")
            return HttpResponseRedirect(reverse('coord_main_panel'))

    return render(request, 'event/edit_event.html', {'form': populated_form})


@login_required
def view_event(request, event_id):
    """View event details."""
    pass


@login_required
def show_event_qr(request, event_id):

    eventuuid = (str(uuid.uuid4())).strip()
    event_details = Event.objects.get(pk=event_id)
    """View Qr code for event."""
    return render(request, 'event/qr.html', {'event_details': event_details, 'eventuuid': eventuuid})


@login_required
def view_dashboard(request, event_id):
    print("eventcall")
    questions_list = Event.question_set.get(pk=event_id)
    print(questions_list)
    return HttpResponseRedirect(reverse('view_dashboard', kwargs={'questions_list': questions_list}))


@login_required
def add_question(request, event_id):
    new_question_form = NewQuestionForm()
    if request.method == 'POST':
        # print(request.POST.get('question_name'))
        # print(request.POST.get('is_active'))
        question_type = request.POST.get('question_type')
        # print(question_type)
        question_type_name = QuestionType.objects.get(pk=question_type)
        # print(question_type_name)
        question_text = request.POST.get('question_name')
        is_active = request.POST.get('is_active')
        is_mandatory = request.POST.get('is_mandatory')
        #question_type_ = question_type_name
        event = event_id
        question = Question.objects.create(question_text=question_text, event_id=event, is_active=is_active, is_mandatory=is_mandatory,
            question_type=question_type_name)


        form_data= request.POST

            # If the question type is single or multiple save the choice with choice text that can be accessed from post params ("choice_(some int)")
        if question_type_name == "Single Choice" or question_type_name == "Multiple Choice":
            for key in form_data:
                print(key)
                print(form_data[key])
                if key.startswith('choice'):
                        # create a choice
                    choice = Choice(choice_text=form_data[key], question= question)
                    choice.save()
        else:
            # create choices for rating
            # 1 star corresponds to choice with text 1
            # 2 star corresponds to choice with text 2
            # and so on... till 5 star
            for i in range(5):
            # create a choice
                choice = Choice(choice_text=str(i+1), question=question)
                choice.save()


        print("question save")
        return HttpResponseRedirect(reverse('view_dashboard', kwargs={'event_id': event_id}))

    return render(request, 'event/addquestion.html', {'form': new_question_form})


def toggle_status(request, question_id):
    print("toggle")
    print(request.method)
    if request.method == 'POST' and request.is_ajax():
        print("accesd")
        print(question_id)
        try:
            question = Question.objects.get(pk=question_id)
            if question.is_active:
                Question.objects.filter(pk=question_id).update(is_active=False)
                return JsonResponse({'status': 'Success', 'msg': 'Fasle successfully'})
            else:
                Question.objects.filter(pk=question_id).update(is_active=True)
                return JsonResponse({'status': 'Success', 'msg': 'true successfully'})

            #return JsonResponse({'status': 'Success', 'msg': 'save successfully'})
        except Question.DoesNotExist:
            return JsonResponse({'status': 'Fail', 'msg': 'Object does not exist'})
    else:
        return JsonResponse({'status': 'Fail', 'msg': 'Not a valid request'})

event/templates/event/addquestion.html
{% extends "base.html" %} {% load i18n %}{% load static %}
{%block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static '/event/css/addquestion.css' %}">
{% endblock %}
{% block content %}
<div class="row m-t-40">
    <div class="col-2">
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" action="" class="form-material">
                    {% csrf_token %} {% for field in form %}
                    <div id="form_group" class="form-group">

                        {{ field.errors }} {{ field.label_tag }} {{ field }}

                    </div>
                    {% endfor %}

                    <!--Add choices dynamically-->
                    <div id="choice_div" onclick="">

                    </div>

                    <br/>
                    <br/>

                    <input type="submit" value="Submit" class="btn btn-rounded btn-success" />
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %} {% block scripts%}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="{% static 'event/js/editevent.js' %}"></script>

<script>

    var i = 0;
    $("#id_question_type").change(function () {

        removeAllNodes();

        var question_type = $("#id_question_type option:selected").html();

        if(question_type=="Single Choice" || question_type=="Multiple Choice"){

            var btn  = document.createElement("button");

            var t = document.createTextNode("Add Choice");

            btn.setAttribute("type", "button");
            btn.setAttribute("class", "btn btn-rounded btn-info");

            btn.appendChild(t);


            btn.onclick = function(){

                addInputField();

            }

            document.getElementById("choice_div").appendChild(btn);
            document.getElementById("choice_div").appendChild(document.createElement("br"));
            document.getElementById("choice_div").appendChild(document.createElement("br"));

            addInputField();

        }else{
        }


        function addInputField(){

            i++;

            var input_a  = document.createElement("input");

            input_a.placeholder =  "Enter Choice";

            input_a.setAttribute("class", "form-control form-control-line");
            input_a.setAttribute("required", "");
            input_a.setAttribute("name", "choice_"+i);
            input_a.style.width = '80%';
            input_a.style.float = 'left';


            var btn  = document.createElement("button");

            var t = document.createTextNode("REMOVE");

            var br_a = document.createElement("br");
            var br_b = document.createElement("br");

            btn.onclick = function(){
                input_a.remove();
                btn.remove();
                br_a.remove();
                br_b.remove();
            }

            btn.setAttribute("type", "button");
            btn.setAttribute("class", "btn btn-rounded btn-danger");
            btn.style.width = '20%';
            btn.style.float = 'right';

            btn.appendChild(t);

            var div_main = document.createElement("div");

            div_main.appendChild(input_a);
            div_main.appendChild(btn);
            div_main.appendChild(br_a);
            div_main.appendChild(br_b);
            document.getElementById("choice_div").appendChild(div_main);
        }

        function removeAllNodes(){
            document.getElementById("choice_div").innerHTML = "";
        };

    });
</script>
{% endblock%}

event/templates/event/edit_event.html
{% extends "base.html" %} {% load i18n %}{% load static %} {% block content %}
<div class="row m-t-40">
    <div class="col-2">
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" action="" class="form-material">
                    {% csrf_token %} {% for field in form %}
                    <div class="fieldWrapper form-group">
                        {{ field.errors }} {{ field.label_tag }} {{ field }}
                    </div>
                    {% endfor %}
                    <input type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block scripts%}
<script src="{% static 'event/js/editevent.js' %}"></script>
{% endblock%}

event/templates/event/new_event_form.html
{% extends "base.html" %} {% load i18n %}{% load static %} 
{%block extra_head %}

{% endblock %}
{% block content %}
<div class="row m-t-40">
    <div class="col-2">
        
    </div>
    <div class="col-8">
        <div class="card">
    <div class="card-body">
        <form method="post" action="" class="form-material">
            {% csrf_token %} {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.event_name.errors }}
                <label for="id_event_name">Event Name:</label>
                <input type="text" class="form-control" name="event_name" maxlength="200" required id="id_event_name" />
            </div>
            <div class="form-group">
                {{ form.date_event.errors }}
                <label for="id_date_event">Date Time: Format(2017-06-04 21:44)</label>
                <input type="text" class="bootstrapMaterialDatePicker form-control" name="date_event" required id="id_date_event" placeholder="2017-06-04 21:44" />
            </div>
            <div class="form-group">
                {{ form.duration.errors }}
                <label for="id_duration">Duration of event:</label>
                <input type="number"  min="0" max="100" class="form-control" name="duration" required id="id_duration" />
            </div>
            <div class="form-group">
                {{ form.description.errors }}
                <label for="id_description">Description:</label>
                <textarea name="description" class="form-control" cols="40" rows="10" required id="id_description">
                </textarea>
            </div>
            <div class="form-group text-center" style="margin:10px;">
                            <div class="col-xs-12 p-b-20">
                                <input class="btn btn-info btn-rounded" type="submit" value="Submit">
                            </div>
                        </div>
        </form>
    </div>
</div>
    </div>
    
</div>
{% endblock %}

{% block scripts%}

{% endblock%}

event/templates/event/qr.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="container ">
	<div class="row m-4">
	<h2>{{event_details.event_name}}</h2>
    <div class="col-12">
        <img align="middle" src="https://api.qrserver.com/v1/create-qr-code/?data=https://localhost/event/amp{{event_details.event_name}}{{eventuuid}}{{event_details.pk}}&amp;size=300x300" />
    </div>
</div>
	
</div>

{% endblock %}

event/templates/event/view_event.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
    <title>{{ event.event_name }}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'assets/plugin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{% static 'css/colors/default-dark.css' %}" id="theme" rel="stylesheet">

    <style>
        @media print { @page { margin: 0; } body { margin: 1.6cm; } }

        tr{
            padding-top: 20px;
        }

    </style>
</head>

<body class="fix-header single-column fix-sidebar">

    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index.html">
                        <!-- Logo icon --><b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="{% static 'assets/images/logo-icon.png' %}" alt="homepage" class="dark-logo" />
                            <!-- Light Logo icon -->
                            <img src="{% static 'assets/images/logo-light-icon.png' %}" alt="homepage" class="light-logo" />
                        </b>
                         <img src="{% static 'assets/images/logo-text.png' %}" alt="homepage" class="dark-logo" />
                         <!-- Light Logo text -->
                         <img src="{% static 'assets/images/logo-light-text.png' %}" class="light-logo" alt="homepage" /></span> </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">

                    </ul>
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark" href="layout-single-column.html" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{% static 'assets/images/users/1.jpg' %}" alt="user" class="profile-pic" /></a>
                            <div class="dropdown-menu dropdown-menu-right animated flipInY">
                                <ul class="dropdown-user">
                                    <li>
                                        <div class="dw-user-box">
                                            <div class="u-img"><img src="{% static 'assets/images/users/1.jpg' %}" alt="user"></div>
                                            <div class="u-text">
                                                <h4>{{ username }}</h4>
                                                <p class="text-muted">{{ email }}</p>
                                                <a href="pages-profile.html" class="btn btn-rounded btn-danger btn-sm">View Profile</a></div>
                                        </div>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="layout-single-column.html#"><i class="fa fa-power-off"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="page-wrapper">

            <div class="container-fluid">
                <div>
                    <div class="col-lg-12">
                        <div class="card" >
                            <div class="card-body" id="card">
                                <div style="width: 50%;float: left">

                                    <h1 class="card-title"><center>Event Overview</center></h1>

                                    <br/>
                                    <h2>{{ event.event_name }}</h2>

                                    <h6>{{ event.timestamp }}</h6>

                                    <br/>

                                    <p>
                                        {{event.description}}
                                    </p>

                                    <h6>Event Coordinator</h6>
                                    <span class="label label-info label-rounded pull-right">{{ event.coordinator }}</span>
                                    <br/>


                                    <br/>
                                    <h2>Sessions</h2>
                                    <br/>

                                    <div class="profiletimeline">



                                        {% for session in event.session_set.all %}

                                            <div class="sl-item">
                                                <div class="sl-left"><div class="timeline-badge success"><button class="btn btn-circle btn-success">{{ forloop.counter }}</button></div></div>
                                                <div class="sl-right">
                                                    <div>
                                                        <h5>{{ session.session_name }}</h5>
                                                        <p><h6>Session duration: <span class="sl-date"> 1 hr 20 min</span></h6></p>
                                                        <p class="m-t-10"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper </p>
                                                    </div>
                                                    <div class="like-comm m-t-20">
                                                        <h6>Presenter</h6>
                                                        <span class="label label-info label-rounded pull-right">{{ session.presenter }}</span>
                                                    </div>
                                                </div>
                                            </div>

                                            {% if forloop.counter != event.session_set.all.count %}
                                                <hr>
                                            {% endif  %}


                                        {% endfor %}



                                    </div>

                                </div>
                                <div style="width: 50%;float: right;text-align: center">
                                    <h1 class="card-title"><center>QR Code</center></h1>

                                    <br/>

                                    <img align="middle" src="https://api.qrserver.com/v1/create-qr-code/?data={{ SITE_URL }}{% url 'attendee:show_event' event.id %}" &amp;size=300x300"
                                         width="300"
                                         height="300" />
                                </div>

                            </div>


                        </div>
                    </div>

                </div>

                <div style="text-align:center">

                    <a onclick="PrintElem()" target="_blank" style="cursor:pointer; ">
                        <button type="button" class="btn btn-info btn-rounded">Print</button>
                    </a>
                </div>


            </div>



        </div>

    </div>
    <script>
        function PrintElem()
        {
            var divElements = document.getElementById('card').innerHTML;
            //Get the HTML of whole page

            var oldPage = document.body.innerHTML;

            // divElements.setAttribute("padding", '16px');
            //Reset the page's HTML with div's HTML only
            document.body.innerHTML =
              "<html><head></head><body style='margin: 16px'>" + '<br/>' + divElements + "</body>";

            //Print Page
            window.print();

            //Restore orignal HTML
            document.body.innerHTML = oldPage;
        }

    </script>
    <script src="{% static 'assets/plugin/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugin/bootstrap/js/bootstrap.min.js' %}"></script>

</body>

</html>